#SMALL PROJECT
#password genarator  only by using numbers
def password():
  import random
  n=int(input("enter the length of the password"))
  list=[]
  for i in range(0,n):
    a=random.randint(0,9)
    list.append(a)
  #print(list)
  random.shuffle(list)
  password=""
  for i in list:
    password=password+str(i)
  print(f"the password which is generated by using numbers is{password}")
password()
#password genarator using numbers ,symbols,lower case and upper case alphabets
def Password_Generator():
  import random
  numbers=['0','1','2','3','4','5','6','7','8','9']
  symbols=['!','#','$','%','&','(',')','*','+']
  alphabets=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
  print("welcome to password genarator")
  n=int(input("enter how many numbers do you want in your password"))
  m=int(input("enter how many symbols do you want in your password"))
  o=int(input("enter how many alphabets do you want in your password"))
  password=[]
  for i in range(n):
    p=random.choice(numbers)
    password.append(p)
  for i in range(m):
    q=random.choice(symbols)
    password.append(q)
  for i in range(o):
    r=random.choice(alphabets)
    password.append(r)
  #print(password)
  random.shuffle(password)
  #print(password)
  p=""
  for i in password:
    p=p+str(i)
  print(f"here is the password by using {n}numbers {m}symbols {o}alphabets is:\n{p}")
  print("have a nice day")
  print("thankyou for using this password generator")
Password_Generator()